blog_app/urls.py
from django.urls import path
from blog_app import views

app_name='blog_app'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create_blog/', views.CreateBlog.as_view(), name='create_blog'),
    path('update_blog/<pk>', views.UpdateBlog.as_view(), name='update_blog'),
    path('blog_detail/<slug:slug>/', views.BlogDetail, name='blog_detail'),
    path('my_blog/', views.MyBlog.as_view(), name='my_blog'),
    path('liked/<int:pk>/', views.Liked, name='liked'),
    path('unliked/<int:pk>/', views.unliked, name='unliked'),
    
  
]

my_blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('',views.index,name='index')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    title = models.CharField(max_length=255, verbose_name='Title of Your Post')
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    content = models.TextField(verbose_name='Write your content Here')
    blog_image = models.ImageField(verbose_name='Image', upload_to='blog_images')
    publish_time = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class comment(models.Model):
    blog_comment = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comments')
    user_comment = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment_content = models.TextField(verbose_name="Comment Here")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return slef.comment_content


class like(models.Model):
    blog_like = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="blog_likes")
    user_like = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_likes")
    

blog_app/forms.py
from django import forms
from blog_app import models


class LikeForm(forms.ModelForm):
    class Meta:
        model = models.like
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.comment
        fields = ('comment_content',)
        

blog_app/views.py
from django.shortcuts import render,HttpResponseRedirect
from blog_app import models
from blog_app import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.views.generic import CreateView, DeleteView,DetailView,UpdateView,ListView,TemplateView,View
import uuid

# Create your views here.

class BlogList(ListView):
    context_object_name = 'blogs'
    model = models.Blog
    template_name = "blog_list.html"
    queryset = models.Blog.objects.order_by('-publish_time')



class CreateBlog(LoginRequiredMixin, CreateView):
    model = models.Blog
    fields = ('title','content','blog_image')
    template_name = "blog_app/create_blog.html"

    def form_valid(self,form):
        current_user = self.request.user
        
        form_obj = form.save(commit=False)
        form_obj.author = current_user
        blog_title = form_obj.title 
        form_obj.slug = blog_title.replace(" ","-") + "-" + str(uuid.uuid4())

        form.save()
        return HttpResponseRedirect(reverse('index'))



class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = models.Blog
    fields = ('title','content','blog_image')
    template_name = "blog_app/update_blog.html"

    def get_success_url(self,**kwargs):
        return reverse_lazy('blog_app:blog_detail', kwargs={'slug':self.object.slug})




@login_required
def BlogDetail(request,slug):
    blog = models.Blog.objects.get(slug=slug)
    comment_form = forms.CommentForm()

    already_liked = models.like.objects.filter(blog_like=blog,user_like=request.user)
    if already_liked:
        liked = True
    
    else:
        liked = False

    if request.method=='POST':
        comment_form = forms.CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False) 
            comment.blog_comment = blog   
            comment.user_comment = request.user
            comment.save()   
            return HttpResponseRedirect(reverse('blog_app:blog_detail', kwargs={'slug':slug}))

    diction = {'blog':blog,'comment_form':comment_form,'liked':liked}

    return render(request,'blog_app/blog_detail.html',context=diction)

@login_required
def Liked(request,pk):
    blog = models.Blog.objects.get(pk=pk)
    current_user = request.user

    already_liked = models.like.objects.filter(blog_like=blog,user_like=current_user)
    if not already_liked:
        liked_post = models.like(blog_like=blog,user_like=current_user)
        liked_post.save()
    
    return HttpResponseRedirect(reverse('blog_app:blog_detail',kwargs={'slug':blog.slug}))


@login_required
def unliked(request,pk):
    blog = models.Blog.objects.get(pk=pk)
    current_user = request.user

    already_liked = models.like.objects.filter(blog_like=blog,user_like=current_user)

    already_liked.delete()

    return HttpResponseRedirect(reverse('blog_app:blog_detail',kwargs={'slug':blog.slug}))


class MyBlog(LoginRequiredMixin,TemplateView):
    template_name = "blog_app/my_blogs.html"

templates/blog_app/blog_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Blog Details
{% endblock title_block %}
    
    
    


{% block body_block %}
<div class="row">
    <div class="col-sm-6 mx-auto text-center">
        <h3>{{ blog.title }}</h3>
        <h5>Posted By: <a href="">{{ blog.author }}</a></h5>
        <i><h6 class="mb-1">Published on: {{ blog.publish_time }}</h6></i>
        <i><h6 class="mb-4">Updated on: {{ blog.updated_date }}</h6></i>
        <h6>{{ blog.blog_likes.count }} Likes | {{ blog.blog_comments.count }} comments</h6>
        
        
    </div>

    <div class="col-sm-6"><img src="/media/{{ blog.blog_image }}" alt="{{ blog.title }}" title="{{ blog.title }}" class="img-fluid" style="display: block; width: 100% \9; height: auto;"></div>

</div>
    
    <div>
        <p>{{ blog.content|linebreaks }}</p>
    </div>
    <hr>
    <div class="row">
        <div class="col-6 text-center">
            {% if liked %}
                  <ul class="list-group">
                    <li class="list-group-item"><a href="{% url 'blog_app:unliked' pk=blog.pk %}" style="text-decoration: none;"><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Unlike </a></li>
                </ul>
            {% else %}
                  <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'blog_app:liked' pk=blog.pk %}" style="text-decoration: none;"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Like </a></li>
                </ul>
            {% endif %}
            
          
        </div>
        <div class="col-6 text-center">
            <ul class="list-group">
                <li class="list-group-item"><a href="" data-bs-toggle="modal" data-bs-target="#staticBackdrop" style="text-decoration: none;"><i class="fa fa-comment-o" aria-hidden="true"></i> Comment</a></li>
            </ul>
        

            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="staticBackdropLabel">Commnet</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <form method="POST">
                          {{ comment_form|crispy }}
                          {% csrf_token %}
                         <input type="submit" name="submit" value="Comment" class="mt-3 btn btn-success">
                          
                      </form>
                    </div>
                    
                  </div>
                </div>
              </div>
        </div>
    </div>
    {% for comment in blog.blog_comments.all %}
    <div class="row">
            <p><a href="">{{ comment.user_comment }}</a>{{ comment.comment_content }}
            <h6>{{ comment.comment_date }}</h6></p>
    </div>
    {% endfor %}
   
{% endblock body_block %}
    
    

templates/blog_app/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title_block %}
    Home
{% endblock title_block %}


{% block body_block %}
    
    {% for blog in blogs %}
        <h3>{{ blog.title }}</h3></a>
        <h6 class="mb-4">{{ blog.publish_time }}</h6>
        <div class="row mx-auto">
            <div class="col-sm-4"><img src="/media/{{ blog.blog_image }}" alt="{{ blog.title }}" title="{{ blog.title }}" class="img-fluid"></div>
            <div class="col-sm-8">
                <p>{{ blog.content|range_filter|linebreaks }} <a href="{% url 'blog_app:blog_detail' slug=blog.slug %}">Read more</a></p>
                <h6>Posted By: <a href="">{{ blog.author }}</a></h6>
                <h6>{{ blog.blog_likes.count }} Likes | {{ blog.blog_comments.count }} comments</h6>
            </div>
        </div>
        <hr>
    {% endfor %}
        
{% endblock body_block %}
    
    

templates/blog_app/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title_block %}
    Create Blog
{% endblock title_block %}



{% block body_block %}
    <div class="col-md-10 mx-auto">
        <h2 class="text-center">Write your Blog Here</h2>
        <form method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
            <input type="submit" name="submit" value="Create Blog" class="btn btn-success form-control m-4">
        </form>
        
    </div>
    
{% endblock body_block %}

templates/blog_app/my_blogs.html
{% extends 'base.html' %}

{% block title_block %}
    My Blogs
{% endblock title_block %}
{% load custom_filters %}
{% block body_block %}
    {% for blog in user.post_author.all %}
    <div class="row">
        <div class="col-sm-6">
            <h3>{{ blog.title }}</h3>
            <h6><i>Published on: {{ blog.publish_time }}</i></h6>
            <h6><i>Updated on: {{ blog.updated_date }}</i></h6>
            <h6>{{ blog.blog_likes.count }} Likes | {{ blog.blog_comments.count }} comments  </h6>
        </div>
        <div class="col-sm-6">
            <img src="/media/{{ blog.blog_image }}" alt="" class="img-fluid">
        </div>
    </div>
    <p> {{ blog.content|range_filter|linebreaks }} <a href="{% url 'blog_app:blog_detail' slug=blog.slug %}" style="text-decoration: none;">Read more</a> </p>
    <a href="{% url 'blog_app:update_blog' pk=blog.pk %}">Edit</a>
    <hr>
    {% endfor %}
{% endblock body_block %}

templates/blog_app/update_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Update Blog
{% endblock title_block %}



{% block body_block %}
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" name="submit" class="btn btn-success form-control mt-4">
    </form>
{% endblock body_block %}