blog_app/urls.py
from django.urls import path
from blog_app import views

app_name='blog_app'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create_blog/', views.CreateBlog.as_view(), name='create_blog'),
    path('update_blog/<pk>', views.UpdateBlog.as_view(), name='update_blog'),
    path('blog_detail/<slug:slug>/', views.BlogDetail, name='blog_detail'),
    path('my_blog/', views.MyBlog.as_view(), name='my_blog'),
    path('liked/<int:pk>/', views.Liked, name='liked'),
    path('unliked/<int:pk>/', views.unliked, name='unliked'),
    
  
]

login_app/urls.py
from django.urls import path
from login_app import views



app_name='login_app'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.Sign_in, name='signin'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/', views.profile_page, name='profile'),
    path('password/', views.pass_change, name='pass_change'),
    path('profile_pic_upload/', views.add_pro_pic, name='profile_pic_upload'),
    path('profile_pic_change/', views.change_pro_pic, name='profile_pic_change'),
    path('update_profile/', views.edit_profile_information, name='update_profile'),
]

my_blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('',views.index,name='index')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete = models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

login_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from login_app import models

class signup_form(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.EmailField(required=True)
    last_name = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name','email', 'password1','password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name','email', 'password')


class change_profile_pic(forms.ModelForm):
    
    class Meta:
        model = models.UserProfile
        fields=('profile_pic',)

login_app/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from login_app import forms

# Create your views here.
def sign_up(request):
    registered = False
    form = forms.signup_form()
    if request.method == 'POST':
        form = forms.signup_form(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    diction = {'registered':registered, 'form':form}
    return render(request,'login_app/sign_up.html', context=diction)



def Sign_in(request):
    
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    
    return render(request,'login_app/sign_in.html',context={'form':form})


@login_required
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile_page(request):
    
    diction={}
    return render(request,'login_app/profile.html',context=diction)

@login_required
def edit_profile_information(request):
    current_user = request.user
    form = forms.UserProfileChange(instance=current_user)

    if request.method == 'POST':
        form = forms.UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = forms.UserProfileChange(instance=current_user)
    
    diction = {'form':form}
    return render(request,'login_app/update_profile.html',context=diction)

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    
    return render(request,'login_app/pass_change.html',context={'form':form,'changed':changed})


@login_required
def add_pro_pic(request):
    current_user = request.user
    form = forms.change_profile_pic()
    if request.method == 'POST':
        form=forms.change_profile_pic(request.POST,request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = current_user
            user_obj.save()
            HttpResponseRedirect(reverse('login_app:profile'))
    diction = {'form':form}
    return render(request,'login_app/profile_pic_add.html',context=diction)

@login_required
def change_pro_pic(request):
    current_user = request.user
    form = forms.change_profile_pic(instance=current_user.user_profile)
    if request.method == 'POST':
        form = forms.change_profile_pic(request.POST, request.FILES, instance=current_user.user_profile)
        if form.is_valid():
            form.save()
            HttpResponseRedirect(reverse('login_app:profile'))
    diction = {'form':form}
    return render(request,'login_app/profile_pic_add.html',context=diction)

templates/login_app/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Password Change
{% endblock title_block %}
   

{% block body_block %}
    
    {% if changed %}
        <div class="aler alert-success">Password Changed Successfully!</div>
    {% else %}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <input type="submit" name="submit" value="Change Password" class="btn btn-danger mt-3">
    </form>
    {% endif %}
{% endblock body_block %}

templates/login_app/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
    Profile
{% endblock title_block %}
    


{% block body_block %}


{% if user.user_profile %}
    <div class="card mb-3 col-md-8 mx-auto text-center">
        <img src="/media/{{ user.user_profile.profile_pic }}" class="img-fluid mx-auto rounded-circle" alt="Profile picture" style="height: 150px; width: 150px;">
        <a href="{% url 'login_app:profile_pic_change' %}" class="btn btn-success col-md-3 mx-auto card-link mt-2">Change profile picture</a>
        <div class="card-body">
        <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">An item</li>
            <li class="list-group-item">A second item</li>
            <li class="list-group-item"><a href="{% url 'login_app:update_profile' %}" class="btn btn-primary card-link"> Edit Profile</a></li>
        </ul>
    </div>
{% else %}
    <div class="card col-md-6 mx-auto text-center">
        <img src="/media/profile_pics/default_profile.jpg" class=" img-fluid mx-auto rounded-circle" alt="Profile picture" style="max-height: 200px; max-width: 200px;">
        <a href=" {% url 'login_app:profile_pic_upload' %}" class="btn btn-success col-md-4 mx-auto ">Add profile picture</a>
        <div class="card-body">
        <h5 class="card-title list-group-item">{{ user.first_name }} {{ user.last_name }}</h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">An item</li>
            <li class="list-group-item">A second item</li>
            <li class="list-group-item"><a href="{% url 'login_app:update_profile' %}" class="btn btn-primary card-link"> Edit Profile Info</a></li>
        </ul>
        </div>
    </div>
{% endif %}
{% endblock body_block %}
    

templates/login_app/profile_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Change Profile Photo
{% endblock title_block %}



{% block body_block %}
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Submit" class="btn btn-success mt-2">
    </form>
{% endblock body_block %}
    

templates/login_app/sign_in.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title_block %}
    Sign In
{% endblock title_block %}


{% block body_block %}
<div class="container">
    <h3 class="text-center m-4">Log In</h3>
    <form method="POST" style="my-auto">
        {{form|crispy}}
        {% csrf_token %}
        <input type="submit" name="submit" value="Sign In" class="form-control btn btn-success mt-4">
    </form>
</div>
    
        
        
{% endblock body_block %}
    
    

templates/login_app/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title_block %}
    Sign Up
{% endblock title_block %}


{% block body_block %}
    {% if registered %}
        <div class="alert alert-success">Congratualtions! Registration Successful. <a href="{% url 'login_app:signin' %}">Login Here</a></div>
    {% else %}
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <input type="submit" name="submit" value="Sign Up" class="btn btn-success form-control">
        </form>
        <h6 style="padding-top: 10px;">Already Have an account? <a href="{% url 'login_app:signin' %}">Login Here</a></h6>
    {% endif %}  
 
{% endblock body_block %}
    
    

templates/login_app/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Update Profile
{% endblock title_block %}



{% block body_block %}
    <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Update Information" class="btn btn-info">
    </form>
{% endblock body_block %}
    