blog_app/urls.py
from django.urls import path
from blog_app import views

app_name='blog_app'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create_blog/', views.CreateBlog.as_view(), name='create_blog'),
    path('update_blog/<pk>', views.UpdateBlog.as_view(), name='update_blog'),
    path('blog_detail/<slug:slug>/', views.BlogDetail, name='blog_detail'),
    path('my_blog/', views.MyBlog.as_view(), name='my_blog'),
    path('liked/<int:pk>/', views.Liked, name='liked'),
    path('unliked/<int:pk>/', views.unliked, name='unliked'),
    
  
]

login_app/urls.py
from django.urls import path
from login_app import views



app_name='login_app'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.Sign_in, name='signin'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/', views.profile_page, name='profile'),
    path('password/', views.pass_change, name='pass_change'),
    path('profile_pic_upload/', views.add_pro_pic, name='profile_pic_upload'),
    path('profile_pic_change/', views.change_pro_pic, name='profile_pic_change'),
    path('update_profile/', views.edit_profile_information, name='update_profile'),
]

my_blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('',views.index,name='index')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title> 
        {% block title_block %}
            
        {% endblock title_block %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background: #0e1d3b;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item" style="padding-right: 30px;">
                <a class="nav-link active" aria-current="page" href="{% url 'blog_app:blog_list' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i> Home</a>
              </li>

              {% if user.is_authenticated %}
              <li class="nav-item" style="padding-right: 30px;">
                <a class="nav-link" aria-current="page" href="{% url 'blog_app:create_blog' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Write Blog</a>
              </li>

              <li class="nav-item" style="padding-right: 30px;">
                <a class="nav-link" aria-current="page" href="{% url 'blog_app:my_blog' %}"><i class="fa fa-archive" aria-hidden="true"></i> My Blog</a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-user-circle" aria-hidden="true"></i> {{user.username}}
                </a>
                <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-left" aria-labelledby="navbarDarkDropdownMenuLink" style="background: #0e1d3b; color:aliceblue">
                  <li><a class="dropdown-item" href="{% url 'login_app:profile' %}"><i class="fa fa-id-card-o" aria-hidden="true"></i>&nbsp; Profile</a></li>
                  <!-- <li><a class="dropdown-item" href="{% url 'blog_app:create_blog' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Write Blog</a></li> -->
                  <!-- <li><a class="dropdown-item" href="{% url 'blog_app:my_blog' %}"><i class="fa fa-archive" aria-hidden="true"></i> My Blogs</a></li> -->
                  <li><a class="dropdown-item" href="{% url 'login_app:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                  
                </ul>
              </li>
            </li>
              {% else %}
              <li class="nav-item" style="padding-right: 30px;">
                <a class="nav-link" href="{% url 'login_app:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item" style="padding-right: 30px;">
                <a class="nav-link" href="{% url 'login_app:signin' %}">Log In</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
        <hr>
      </nav>
      
    
    <div class="container mt-4">
        
        {% block body_block %}
            
        {% endblock body_block %}
            
    </div>




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>